#!/usr/bin/env zsh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#alias cd='cd;ls'

alias py='python3'
alias ipy='ipython3'
alias bpy='bpython'

alias e='emacs'
alias en='emacs --no-window-system'
alias ec='emacsclient --tty'
alias v='vi'

alias clearall='clear && clear'

alias ascdoc='asciidoctor'

alias rsync-git='rsync --exclude=".git"'
alias rsync-gitignore='rsync --exclude=".git" --filter=":- .gitignore"'

# gomod go get -v golang.org/x/tools/gopls@latest
alias gomod='GO111MODULE=on GOPROXY=https://goproxy.io'
alias gomodget='gomod go get -u -v'
# electronproxy npx create-electron-app --template=typescript tapp
alias electronproxy='ELECTRON_MIRROR=https://cdn.npm.taobao.org/dist/electron/'
# tselectronapp <appname>
alias tselectronapp='electronproxy npx create-electron-app --template=typescript'

# usewslproxy set WSL_PROXY_PORT in custom.sh
alias usewslproxy='http_proxy=http://$(getwslhost):${WSL_PROXY_PORT} https_proxy=http://$(getwslhost):${WSL_PROXY_PORT}'

# useautoproxy set AUTO_PROXY_PORT in custom.sh
alias useautoproxy='http_proxy=http://$(get_auto_proxy_host):${AUTO_PROXY_PORT} https_proxy=http://$(get_auto_proxy_host):${AUTO_PROXY_PORT}'

# Alias for docker
alias dkps='docker ps'
alias dkpsa='docker ps -a'
alias dkimg='docker images'
alias dkrm='docker rm'


# Alias for git
alias ga='git add --verbose'
alias gau='ga --update'
alias gap='ga --patch'

alias gcm='git commit -v -m'
alias gca='git commit -v --amend --date=now'
alias gcma='git commit -v --amend --date=now -m'
alias gcam='git commit -v --amend --date=now -m'
alias gcanoedit='git commit -v --amend --date=now --no-edit'

alias glr='git pull --rebase'

alias gpf='git push --force'
alias gpfgh='usewslproxy gpf gh'

alias gfgh='usewslproxy gf gh'
alias gpgh='usewslproxy gp gh'

alias gdc='git diff --cached'

alias gdtl="git difftool"
alias gdtm="git difftool --tool=meld"

alias gig="go install -v --gcflags \"-N -l\""
alias gbg="go build -v --gcflags \"-N -l\""
