#!/usr/bin/env zsh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias cd='_cdls'

alias py='python3'
alias ipy='ipython3'
alias bpy='bpython'

alias e='emacs'
alias en='emacs --no-window-system'
alias ec='emacsclient --tty'
alias v='vi'

alias ascdoc='asciidoctor'

alias rsync-git='rsync --exclude=".git"'
alias rsync-gitignore='rsync --exclude=".git" --filter=":- .gitignore"'

alias goproxy='GO111MODULE=on GOPROXY=https://goproxy.io'

# Alias for git
alias ga='git add --verbose'
alias gau='ga --update'
alias gap='ga --patch'

alias gcm='git commit -v -m'

alias gdc='git diff --cached'

alias gdtl="git difftool"
alias gdtm="git difftool --tool=meld"

alias gig="go install -v --gcflags \"-N -l\""
alias gbg="go build -v --gcflags \"-N -l\""

