from peewee import *

# generated by `python -m pwiz center.db3 > db_center.py`

database = SqliteDatabase('center.db3')

class BaseModel(Model):
    class Meta:
        database = database

class Label(BaseModel):
    create_time = TextField()
    extra = TextField()
    id = TextField(unique=True)
    internal_id = AutoField()
    name = TextField(unique=True)
    parent_id = TextField(index=True)
    update_time = TextField()

    class Meta:
        table_name = 'label'

class Object(BaseModel):
    content = TextField()
    create_time = TextField()
    id = TextField(unique=True)
    internal_id = AutoField()
    object_type_id = TextField(index=True)
    title = TextField(constraints=[SQL("DEFAULT ''")])
    update_time = TextField()

    class Meta:
        table_name = 'object'

class ObjectLabelRel(BaseModel):
    create_time = TextField()
    internal_id = AutoField()
    label_id = TextField(unique=True)
    object_id = TextField(unique=True)

    class Meta:
        table_name = 'object_label_rel'
        indexes = (
            (('object_id', 'label_id'), True),
        )

class ObjectRel(BaseModel):
    create_time = TextField()
    internal_id = AutoField()
    parent_id = TextField(index=True)
    sub_id = TextField(index=True)
    update_time = TextField()

    class Meta:
        table_name = 'object_rel'
        indexes = (
            (('parent_id', 'sub_id'), True),
        )

class ObjectType(BaseModel):
    create_time = TextField()
    description = TextField()
    id = TextField(unique=True)
    internal_id = AutoField()
    name = TextField(unique=True)
    update_time = TextField()

    class Meta:
        table_name = 'object_type'

class SqliteSequence(BaseModel):
    name = BareField(null=True)
    seq = BareField(null=True)

    class Meta:
        table_name = 'sqlite_sequence'
        primary_key = False

